language: python
python: 3.4
env:
  - TOXENV=py27-django111-test
  - TOXENV=py34-django111-test
  - TOXENV=py34-django20-test
  - TOXENV=py27-flake
  - TOXENV=py34-flake
  - TOXENV=checkmanifest

 # this is needed for python 3.5 and 3.6
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35-django111-test
  - python: 3.5
    env: TOXENV=py35-django20-test
  - python: 3.5
    env: TOXENV=py35-flake
  - python: 3.6
    env: TOXENV=py36-django111-test
  - python: 3.6
    env: TOXENV=py36-django20-test
  - python: 3.6
    env: TOXENV=py36-django21-test
  - python: 3.6
    env: TOXENV=py36-django22-test
  - python: 3.6
    env: TOXENV=py36-django30-test
  - python: 3.6
    env: TOXENV=py36-flake

install:
  - pip install coveralls tox>=2.1
script:
  - tox
after_script:
  - coveralls
sudo: false
